; this is the INI file for database connection
[database connection] 
dsn="mysql:host=127.0.0.1;dbname=cst8257project;port=3306;charset=utf8"

scriptUser="ctaguan"
adminUser="ADMINSCRIPTUSER"

scriptPassword="password1234"
